---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Service
metadata:
  name: helm-service
  namespace: dev
spec:
  selector:
    app: zomato
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-deploy
  namespace: dev
spec:
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
       containers:
         - name: cont-1
           image: harishdoc098/chanti:japan
           ports:
             - containerPort: 80
